unet_additional_kwargs:
  unet_use_cross_frame_attention: false
  unet_use_temporal_attention: false
  use_motion_module: true
  motion_module_resolutions:
  - 1
  - 2
  - 4
  - 8
  motion_module_mid_block: false
  motion_module_decoder_only: false
  motion_module_type: Vanilla
  motion_module_kwargs:
    num_attention_heads: 8
    num_transformer_block: 1
    attention_block_types:
    - Temporal_Self
    - Temporal_Self
    temporal_position_encoding: true
    temporal_position_encoding_max_len: 24
    temporal_attention_dim_div: 1
  # Addition for image embeddings
  use_image_condition            : false

noise_scheduler_kwargs:
  algorithm_type: "dpmsolver++"
  beta_end: 0.02
  beta_schedule: "linear"
  beta_start: 0.0001
  dynamic_thresholding_ratio: 0.995
  euler_at_final: false
  lower_order_final: true
  num_train_timesteps: 1000
  prediction_type: "epsilon"
  sample_max_value: 1.0
  solver_order: 2
  solver_type: "midpoint"
  steps_offset: 0
  thresholding: false
  timestep_spacing: "linspace"
  trained_betas: null
  use_karras_sigmas: false
  use_lu_lambdas: false
  variance_type: null